export enum ControlType {
    TextBlock = 0,
    TextBox = 1,
    Button = 2,
    DataGrid = 3,
    ComboBox = 4,
    ComboBoxForEnum = 5,
    CheckBox = 6,
    Panel = 7,
    TreeView = 8,
    TabControl = 9,
    TabItem = 10,
    ProgressBar = 11,
    StepProgressBar = 12,
    NumberBox = 13,
    View = 14,
    DateTimeFilter = 15,
    // Form = 16,
    CustomEnumControl = 17,
    RadioControl = 18,
    DropDownButton = 19,
    DropDownChildButton = 20,
    DateSelect = 21,
    DateTimeSelect = 22,
    // TimeSelect = 23,
}